export enum Register {
  R0          = 0,
  R1          = 1,
  R2          = 2,
  R3          = 3,
  R4          = 4,
  R5          = 5,
  R6          = 6,
  R7          = 7,
  A           = 8,
  PC          = 9,
  IR          = 10,
  MAR         = 11,
  MDR         = 12,
  FR          = 13,
  SP          = 14,
  FP          = 15,
  IRQ         = 16,
  IE          = 17,
}